import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createTestDb,createUser,asUser,asAnon,setTestTime} from './helper.mjs';
async function setup(){const db=await createTestDb();await setTestTime(db,'2026-09-26T12:00:00+09:00');await db.exec("update public.prizes set active=true,effective_week='2026-09-21' where weekly_refill; update public.app_settings set value='1' where key='prize_rate';");return db;}
async function player(db,name,staff=false){const id=randomUUID();await createUser(db,id);await asUser(db,id,()=>db.query('select public.register_player($1,1,null)',[name]));if(staff)await db.query('insert into public.staff(user_id) values($1)',[id]);await db.query("insert into public.nut_ledger(player_id,amount,reason,ref,day) values($1,2000,'test','setup',public.jst_today())",[id]);return id;}
async function pull(db,id,count=1){return asUser(db,id,async()=> (await db.query('select public.pull_gacha($1) as result',[count])).rows[0].result);}
test('週1枚: 10連内・別ユーザー・引換券削除後でも2枚目を発行しない。月曜JSTに1枚へ戻る',async()=>{const db=await setup();try{const a=await player(db,'A');const b=await player(db,'B');let result=await pull(db,a,10);assert.equal(result.results.filter(i=>i.kind==='prize').length,1);assert.equal((await pull(db,b,10)).results.filter(i=>i.kind==='prize').length,0);const rate=await asUser(db,a,async()=> (await db.query('select public.gacha_rates() as r')).rows[0].r);assert.equal(rate.prize_rate,0);assert.equal(rate.weekly_remaining,0);await db.exec('delete from public.prize_tickets');assert.equal((await pull(db,b)).results[0].kind,'item');await setTestTime(db,'2026-09-27T23:59:59+09:00');assert.equal((await pull(db,b)).results[0].kind,'item');await setTestTime(db,'2026-09-28T00:00:00+09:00');assert.equal((await pull(db,b)).results[0].kind,'prize');assert.equal((await db.query('select count(*)::int n from public.weekly_prize_awards')).rows[0].n,2);}finally{await db.close();}});
test('スタッフは学年なし・ランキングと実物景品から除外。木の実残高と着せ替えは利用可能',async()=>{const db=await setup();try{const staff=await player(db,'Staff',true);const student=await player(db,'Student');const p=(await db.query('select grade,account_type from public.players where id=$1',[staff])).rows[0];assert.deepEqual(p,{grade:null,account_type:'staff'});const result=await pull(db,staff,10);assert.equal(result.results.filter(i=>i.kind==='prize').length,0);assert.equal(result.balance,1950);assert.equal((await pull(db,student)).results[0].kind,'prize');for(const view of ['ranking_learn_week','ranking_commit_week']){assert.equal((await db.query(`select count(*)::int n from public.${view} where nickname='Staff'`)).rows[0].n,0);}const rate=await asUser(db,staff,async()=> (await db.query('select public.gacha_rates() as r')).rows[0].r);assert.equal(rate.staff_mode,true);assert.equal(rate.prize_rate,0);await db.exec('select public.advance_grades()');assert.equal((await db.query('select grade from public.players where id=$1',[staff])).rows[0].grade,null);}finally{await db.close();}});
test('週間コミット1位: スタッフ除外・同点順・ガチャとは別枠・締め直しで重複なし',async()=>{const db=await setup();try{const a=await player(db,'A');const b=await player(db,'B');const staff=await player(db,'Staff',true);for(const [id,amount] of [[a,10],[b,10],[staff,100]])await db.query("insert into public.points(player_id,kind,reason,amount,week_start,day) values($1,'commit','test',$2,'2026-09-21','2026-09-26')",[id,amount]);await pull(db,b);await setTestTime(db,'2026-09-28T00:05:00+09:00');await db.exec("select public.close_week('2026-09-21');select public.close_week('2026-09-21');");const awards=(await db.query("select channel,player_id from public.weekly_prize_awards where week_start='2026-09-21' order by channel")).rows;assert.deepEqual(awards,[{channel:'gacha',player_id:b},{channel:'ranking',player_id:a}]);assert.equal((await db.query('select count(*)::int n from public.weekly_results where player_id=$1',[staff])).rows[0].n,0);await assert.rejects(db.exec("select public.close_week('2026-09-28')"),/invalid_reward_week/);}finally{await db.close();}});
test('0ポイント・停止中の券・開始前の週はランキング券を発行しない',async()=>{const db=await setup();try{await player(db,'A');await setTestTime(db,'2026-09-28T00:05:00+09:00');await db.exec("select public.close_week('2026-09-21')");assert.equal((await db.query("select count(*)::int n from public.weekly_prize_awards")).rows[0].n,0);await db.exec("update public.prizes set active=false where reward_channel='gacha'");const a=(await db.query("select id from public.players where nickname='A'")).rows[0].id;assert.equal((await pull(db,a)).results[0].kind,'item');}finally{await db.close();}});
test('利用状況はスタッフだけ。生徒・匿名は管理関数と週次台帳にアクセスできない',async()=>{const db=await setup();try{const staff=await player(db,'Staff',true);const student=await player(db,'Student');await pull(db,staff,10);await pull(db,student,10);const overview=await asUser(db,staff,async()=> (await db.query('select public.staff_reward_overview() as r')).rows[0].r);assert.equal(overview.stats.students,1);assert.equal(overview.stats.staff,1);assert.equal(overview.stats.weekly_pulls,11);assert.equal(overview.stats.gacha_issued,1);await asUser(db,student,async()=>{await assert.rejects(db.exec('select public.staff_reward_overview()'),/not_a_staff/);await assert.rejects(db.exec('select * from public.weekly_prize_awards'),/permission denied/);await assert.rejects(db.exec("select public.award_weekly_ranking('2026-09-21')"),/permission denied/);await assert.rejects(db.exec("update public.players set account_type='staff',grade=null"),/permission denied/);});await asAnon(db,async()=>{await assert.rejects(db.exec('select public.staff_reward_overview()'),/permission denied/);const rules=(await db.query('select public.weekly_reward_rules() as r')).rows[0].r;assert.ok(rules.ranking);});}finally{await db.close();}});
